version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jcourse
      POSTGRES_PASSWORD: jcourse
      POSTGRES_DB: jcourse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  vectordb:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: jcourse
      POSTGRES_PASSWORD: jcourse
      POSTGRES_DB: jcourse
    volumes:
      - vector_data:/var/lib/postgresql/data
    ports:
      - 5433:5432


  pgAdmin:
    container_name: pgAdmin
    # restart: unless-stopped
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_LISTEN_PORT: 5050
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
        - "5050:5050"


  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
volumes:
  postgres_data:
  pgadmin:
  vector_data: