// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"jcourse_go/model/po"
)

func newUserPO(db *gorm.DB, opts ...gen.DOOption) userPO {
	_userPO := userPO{}

	_userPO.userPODo.UseDB(db, opts...)
	_userPO.userPODo.UseModel(&po.UserPO{})

	tableName := _userPO.userPODo.TableName()
	_userPO.ALL = field.NewAsterisk(tableName)
	_userPO.ID = field.NewInt64(tableName, "id")
	_userPO.CreatedAt = field.NewTime(tableName, "created_at")
	_userPO.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userPO.Username = field.NewString(tableName, "username")
	_userPO.Email = field.NewString(tableName, "email")
	_userPO.Password = field.NewString(tableName, "password")
	_userPO.UserRole = field.NewString(tableName, "user_role")
	_userPO.Avatar = field.NewString(tableName, "avatar")
	_userPO.Department = field.NewString(tableName, "department")
	_userPO.Type = field.NewString(tableName, "type")
	_userPO.Major = field.NewString(tableName, "major")
	_userPO.Degree = field.NewString(tableName, "degree")
	_userPO.Grade = field.NewString(tableName, "grade")
	_userPO.Bio = field.NewString(tableName, "bio")
	_userPO.Points = field.NewInt64(tableName, "points")
	_userPO.LastSeenAt = field.NewTime(tableName, "last_seen_at")
	_userPO.UserPointDetails = userPOHasManyUserPointDetails{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserPointDetails", "po.UserPointDetailPO"),
		User: struct {
			field.RelationField
			UserPointDetails struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("UserPointDetails.User", "po.UserPO"),
			UserPointDetails: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserPointDetails.User.UserPointDetails", "po.UserPointDetailPO"),
			},
		},
	}

	_userPO.fillFieldMap()

	return _userPO
}

type userPO struct {
	userPODo

	ALL              field.Asterisk
	ID               field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time
	Username         field.String
	Email            field.String
	Password         field.String
	UserRole         field.String
	Avatar           field.String
	Department       field.String
	Type             field.String
	Major            field.String
	Degree           field.String
	Grade            field.String
	Bio              field.String
	Points           field.Int64
	LastSeenAt       field.Time
	UserPointDetails userPOHasManyUserPointDetails

	fieldMap map[string]field.Expr
}

func (u userPO) Table(newTableName string) *userPO {
	u.userPODo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userPO) As(alias string) *userPO {
	u.userPODo.DO = *(u.userPODo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userPO) updateTableName(table string) *userPO {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.Username = field.NewString(table, "username")
	u.Email = field.NewString(table, "email")
	u.Password = field.NewString(table, "password")
	u.UserRole = field.NewString(table, "user_role")
	u.Avatar = field.NewString(table, "avatar")
	u.Department = field.NewString(table, "department")
	u.Type = field.NewString(table, "type")
	u.Major = field.NewString(table, "major")
	u.Degree = field.NewString(table, "degree")
	u.Grade = field.NewString(table, "grade")
	u.Bio = field.NewString(table, "bio")
	u.Points = field.NewInt64(table, "points")
	u.LastSeenAt = field.NewTime(table, "last_seen_at")

	u.fillFieldMap()

	return u
}

func (u *userPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userPO) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 17)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["username"] = u.Username
	u.fieldMap["email"] = u.Email
	u.fieldMap["password"] = u.Password
	u.fieldMap["user_role"] = u.UserRole
	u.fieldMap["avatar"] = u.Avatar
	u.fieldMap["department"] = u.Department
	u.fieldMap["type"] = u.Type
	u.fieldMap["major"] = u.Major
	u.fieldMap["degree"] = u.Degree
	u.fieldMap["grade"] = u.Grade
	u.fieldMap["bio"] = u.Bio
	u.fieldMap["points"] = u.Points
	u.fieldMap["last_seen_at"] = u.LastSeenAt

}

func (u userPO) clone(db *gorm.DB) userPO {
	u.userPODo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userPO) replaceDB(db *gorm.DB) userPO {
	u.userPODo.ReplaceDB(db)
	return u
}

type userPOHasManyUserPointDetails struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		UserPointDetails struct {
			field.RelationField
		}
	}
}

func (a userPOHasManyUserPointDetails) Where(conds ...field.Expr) *userPOHasManyUserPointDetails {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userPOHasManyUserPointDetails) WithContext(ctx context.Context) *userPOHasManyUserPointDetails {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userPOHasManyUserPointDetails) Session(session *gorm.Session) *userPOHasManyUserPointDetails {
	a.db = a.db.Session(session)
	return &a
}

func (a userPOHasManyUserPointDetails) Model(m *po.UserPO) *userPOHasManyUserPointDetailsTx {
	return &userPOHasManyUserPointDetailsTx{a.db.Model(m).Association(a.Name())}
}

type userPOHasManyUserPointDetailsTx struct{ tx *gorm.Association }

func (a userPOHasManyUserPointDetailsTx) Find() (result []*po.UserPointDetailPO, err error) {
	return result, a.tx.Find(&result)
}

func (a userPOHasManyUserPointDetailsTx) Append(values ...*po.UserPointDetailPO) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userPOHasManyUserPointDetailsTx) Replace(values ...*po.UserPointDetailPO) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userPOHasManyUserPointDetailsTx) Delete(values ...*po.UserPointDetailPO) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userPOHasManyUserPointDetailsTx) Clear() error {
	return a.tx.Clear()
}

func (a userPOHasManyUserPointDetailsTx) Count() int64 {
	return a.tx.Count()
}

type userPODo struct{ gen.DO }

type IUserPODo interface {
	gen.SubQuery
	Debug() IUserPODo
	WithContext(ctx context.Context) IUserPODo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserPODo
	WriteDB() IUserPODo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserPODo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserPODo
	Not(conds ...gen.Condition) IUserPODo
	Or(conds ...gen.Condition) IUserPODo
	Select(conds ...field.Expr) IUserPODo
	Where(conds ...gen.Condition) IUserPODo
	Order(conds ...field.Expr) IUserPODo
	Distinct(cols ...field.Expr) IUserPODo
	Omit(cols ...field.Expr) IUserPODo
	Join(table schema.Tabler, on ...field.Expr) IUserPODo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserPODo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserPODo
	Group(cols ...field.Expr) IUserPODo
	Having(conds ...gen.Condition) IUserPODo
	Limit(limit int) IUserPODo
	Offset(offset int) IUserPODo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPODo
	Unscoped() IUserPODo
	Create(values ...*po.UserPO) error
	CreateInBatches(values []*po.UserPO, batchSize int) error
	Save(values ...*po.UserPO) error
	First() (*po.UserPO, error)
	Take() (*po.UserPO, error)
	Last() (*po.UserPO, error)
	Find() ([]*po.UserPO, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.UserPO, err error)
	FindInBatches(result *[]*po.UserPO, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*po.UserPO) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserPODo
	Assign(attrs ...field.AssignExpr) IUserPODo
	Joins(fields ...field.RelationField) IUserPODo
	Preload(fields ...field.RelationField) IUserPODo
	FirstOrInit() (*po.UserPO, error)
	FirstOrCreate() (*po.UserPO, error)
	FindByPage(offset int, limit int) (result []*po.UserPO, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserPODo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userPODo) Debug() IUserPODo {
	return u.withDO(u.DO.Debug())
}

func (u userPODo) WithContext(ctx context.Context) IUserPODo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userPODo) ReadDB() IUserPODo {
	return u.Clauses(dbresolver.Read)
}

func (u userPODo) WriteDB() IUserPODo {
	return u.Clauses(dbresolver.Write)
}

func (u userPODo) Session(config *gorm.Session) IUserPODo {
	return u.withDO(u.DO.Session(config))
}

func (u userPODo) Clauses(conds ...clause.Expression) IUserPODo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userPODo) Returning(value interface{}, columns ...string) IUserPODo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userPODo) Not(conds ...gen.Condition) IUserPODo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userPODo) Or(conds ...gen.Condition) IUserPODo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userPODo) Select(conds ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userPODo) Where(conds ...gen.Condition) IUserPODo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userPODo) Order(conds ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userPODo) Distinct(cols ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userPODo) Omit(cols ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userPODo) Join(table schema.Tabler, on ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userPODo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserPODo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userPODo) RightJoin(table schema.Tabler, on ...field.Expr) IUserPODo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userPODo) Group(cols ...field.Expr) IUserPODo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userPODo) Having(conds ...gen.Condition) IUserPODo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userPODo) Limit(limit int) IUserPODo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userPODo) Offset(offset int) IUserPODo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPODo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userPODo) Unscoped() IUserPODo {
	return u.withDO(u.DO.Unscoped())
}

func (u userPODo) Create(values ...*po.UserPO) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userPODo) CreateInBatches(values []*po.UserPO, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userPODo) Save(values ...*po.UserPO) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userPODo) First() (*po.UserPO, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.UserPO), nil
	}
}

func (u userPODo) Take() (*po.UserPO, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.UserPO), nil
	}
}

func (u userPODo) Last() (*po.UserPO, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.UserPO), nil
	}
}

func (u userPODo) Find() ([]*po.UserPO, error) {
	result, err := u.DO.Find()
	return result.([]*po.UserPO), err
}

func (u userPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.UserPO, err error) {
	buf := make([]*po.UserPO, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userPODo) FindInBatches(result *[]*po.UserPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userPODo) Attrs(attrs ...field.AssignExpr) IUserPODo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userPODo) Assign(attrs ...field.AssignExpr) IUserPODo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userPODo) Joins(fields ...field.RelationField) IUserPODo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userPODo) Preload(fields ...field.RelationField) IUserPODo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userPODo) FirstOrInit() (*po.UserPO, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.UserPO), nil
	}
}

func (u userPODo) FirstOrCreate() (*po.UserPO, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.UserPO), nil
	}
}

func (u userPODo) FindByPage(offset int, limit int) (result []*po.UserPO, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userPODo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userPODo) Delete(models ...*po.UserPO) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userPODo) withDO(do gen.Dao) *userPODo {
	u.DO = *do.(*gen.DO)
	return u
}
