// Code generated by codegen.go; DO NOT EDIT.

package types

// PointEventType 相关方法

// IsAPointEventType 判断值是否属于 PointEventType 类型
func IsAPointEventType(s string) bool {
	switch s {
	case "review":
		return true
	case "like":
		return true
	case "be_liked":
		return true
	case "admin_change":
		return true
	case "init":
		return true
	case "transfer":
		return true
	case "reward":
		return true
	case "punish":
		return true
	case "withdraw":
		return true
	case "consume":
		return true
	case "redeem":
		return true
	default:
		return false
	}
}

// Values 返回所有 PointEventType 的值
func (t PointEventType) Values() []string {
	return []string{
		"review",
		"like",
		"be_liked",
		"admin_change",
		"init",
		"transfer",
		"reward",
		"punish",
		"withdraw",
		"consume",
		"redeem",
	}
}

// String 返回 PointEventType 的字符串表示
func (t PointEventType) String() string {
	return string(t)
}
