// Code generated by codegen.go; DO NOT EDIT.

package types

// SettingType 相关方法

// IsASettingType 判断值是否属于 SettingType 类型
func IsASettingType(s string) bool {
	switch s {
	case "string":
		return true
	case "int":
		return true
	case "bool":
		return true
	default:
		return false
	}
}

// Values 返回所有 SettingType 的值
func (t SettingType) Values() []string {
	return []string{
		"string",
		"int",
		"bool",
	}
}

// String 返回 SettingType 的字符串表示
func (t SettingType) String() string {
	return string(t)
}
