// Code generated by codegen.go; DO NOT EDIT.

package types

// UserRole 相关方法

// IsAUserRole 判断值是否属于 UserRole 类型
func IsAUserRole(s string) bool {
	switch s {
	case "normal":
		return true
	case "admin":
		return true
	default:
		return false
	}
}

// Values 返回所有 UserRole 的值
func (t UserRole) Values() []string {
	return []string{
		"normal",
		"admin",
	}
}

// String 返回 UserRole 的字符串表示
func (t UserRole) String() string {
	return string(t)
}
