// Code generated by codegen.go; DO NOT EDIT.

package types

// RatingRelatedType 相关方法

// IsARatingRelatedType 判断值是否属于 RatingRelatedType 类型
func IsARatingRelatedType(s string) bool {
	switch s {
	case "course":
		return true
	case "teacher":
		return true
	case "training_plan":
		return true
	default:
		return false
	}
}

// Values 返回所有 RatingRelatedType 的值
func (t RatingRelatedType) Values() []string {
	return []string{
		"course",
		"teacher",
		"training_plan",
	}
}

// String 返回 RatingRelatedType 的字符串表示
func (t RatingRelatedType) String() string {
	return string(t)
}
