// Code generated by codegen.go; DO NOT EDIT.

package types

// UserType 相关方法

// IsAUserType 判断值是否属于 UserType 类型
func IsAUserType(s string) bool {
	switch s {
	case "student":
		return true
	case "faculty":
		return true
	default:
		return false
	}
}

// Values 返回所有 UserType 的值
func (t UserType) Values() []string {
	return []string{
		"student",
		"faculty",
	}
}

// String 返回 UserType 的字符串表示
func (t UserType) String() string {
	return string(t)
}
