# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: jcourse
          POSTGRES_DB: jcourse
          POSTGRES_USER: jcourse
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_PASSWORD: jcourse
      POSTGRES_HOST: localhost
      REDIS_HOST: localhost

    steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Build Api
      run: go build -v ./cmd/api/main.go

    - name: Build Worker
      run: go build -v ./cmd/worker/main.go

    - name: Test
      run: go test -v ./...
